project:
  type: book
  output-dir: docs

toc: true
number-sections: true
toc-depth: 3
number-depth: 4
bibliography: book.bib
csl: C:/Users/Xinli/Documents/ims.csl

crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)

execute: 
  freeze: auto

jupyter: base23

format:
  html:
    theme: 
      - cosmo
    code-block-bg: true
    code-block-border-left: true 
    code-line-numbers: true
    highlight-style: atom-one

book:
  title: "Datasets Collection"
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd    
    - contents/breast_cancer.qmd
    - contents/datingtestset.qmd
    - contents/ds4psy.qmd
    - contents/horse_colic.qmd
    - contents/iris.qmd
    - contents/mnist.qmd
    - contents/plants_survival.qmd
    - contents/random.qmd
    - contents/titanic.qmd    
  sidebar:
    style: floating
    pinned: true
    align: center
    border: true
    search: true
    collapse-level: 1
  navbar:
    subtitle: "Fall 2023"
  page-navigation: true


    



