project:
  type: book
  output-dir: docs

toc: true
number-sections: false
toc-depth: 3
number-depth: 4
bibliography: book.bib
csl: ims.csl

crossref:
  labels: arabic        # (default is arabic)
  subref-labels: roman i # (default is alpha a)

execute: 
  freeze: auto
  eval: false


metadata-files:
  - _variables.yml

jupyter: core

format:
  bookup-html:
        toc: true
        toc-depth: 3
        css: blocks.css

book:
  title: "Datasets Collection"
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: Regression
      chapters:
        - contents/regression/QSR.qmd
        - contents/regression/student_performance.qmd
        - contents/regression/bike_sharing.qmd
        - contents/regression/auto_mpg.qmd
        - contents/regression/wine_quality.qmd
        - contents/regression/heart_disease.qmd
        - contents/regression/forest_fires.qmd
        - contents/regression/energy_efficiency.qmd
        - contents/regression/airfoil_self_noise.qmd
        - contents/regression/parkinsons_telemonitoring.qmd
        - contents/regression/abalone.qmd
        - contents/regression/concrete_compressive_strength.qmd
        - contents/regression/electrical_grid_stability.qmd
        - contents/regression/seoul_bike_sharing.qmd
        - contents/regression/gas_turbine_emissions.qmd
        - contents/regression/superconductivity.qmd
        - contents/regression/appliances_energy_prediction.qmd
        - contents/regression/air_quality.qmd
        - contents/regression/communities_and_crime_unnormalized.qmd
        - contents/regression/real_estate_valuation.qmd
        - contents/regression/possum.qmd
    - part: Classification
      chapters:
        - contents/classification/adult.qmd
        - contents/classification/breast_cancer.qmd
        - contents/classification/datingtestset.qmd
        - contents/classification/horse_colic.qmd
        - contents/classification/iris.qmd
        - contents/classification/kagglediabetes.qmd
        - contents/classification/littlerockcrime.qmd
        - contents/classification/mnist.qmd
        - contents/classification/plants_survival.qmd
        - contents/classification/random.qmd
        - contents/classification/titanic.qmd
    - part: No Targets
      chapters:
        - contents/no_targets/ds4psy.qmd
        - contents/no_targets/faker.qmd
  sidebar:
    style: "docked"
    pinned: false
    align: center
    border: true
    search: true
    collapse-level: 1
    title: "Datasets Collection <br> {{< meta datetime.semester >}} {{< meta datetime.year >}}"
  # navbar:
  #   subtitle: "good"
  page-navigation: true
  bread-crumbs: false
  search: true
  reader-mode: true
